dist: xenial
jdk:
  - openjdk8
before_install:
  - sudo apt update
  - sudo apt install -y pkg-config python3 python3-pip python3-setuptools ninja-build
  - sudo pip3 install --upgrade pip
  - pip3 install --user meson
  - ./nasm-build.sh
script:
  - ./travis-build.sh
